server:
  port: 8080
  
 # let's add database configuration
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/task_records
      username: root
      password: 2468
  jpa:  #add jpa and hibernate configuration
    generate-ddl: true #  Hibernate (the JPA implementation used by Spring Boot) should automatically generate the database schema DDL (Data Definition Language) based on your entity classes.
    hibernate:
      ddl-auto: update # whenever we make any changes it will automatically update to db
    show-sql: true #set this is to true so that we can see sql queries in console.
        