server:
  port: 8080

# Let's add database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskDB
    username: root
    password: aqil@2468
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update # Whenever you make any changes, it will automatically update the database.
    show-sql: true # Set this to true so that you can see SQL queries in the console.
 # set this to true so that we can see SQL queries in the console.

